# Generated by Django 6.0 on 2026-09-29 06:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="nombre")),
                (
                    "slug",
                    models.SlugField(max_length=180, unique=True, verbose_name="slug"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="precio",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="products/", verbose_name="imagen"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "badge_text",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="etiqueta"
                    ),
                ),
                (
                    "includes_case",
                    models.BooleanField(default=False, verbose_name="incluye estuche"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="creado"),
                ),
            ],
            options={
                "verbose_name": "producto",
                "verbose_name_plural": "productos",
                "ordering": ["created_at", "pk"],
            },
        ),
    ]
