# Generated by Django 6.0 on 2026-09-29 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, upload_to="products/", verbose_name="imagen"
            ),
        ),
        migrations.CreateModel(
            name="ProductBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("connection", "Conexión"),
                            ("noise", "Cancelación de ruido"),
                            ("warranty", "Garantía"),
                            ("magsafe", "MagSafe"),
                            ("design", "Diseño"),
                        ],
                        max_length=16,
                        verbose_name="icono",
                    ),
                ),
                ("text", models.CharField(max_length=160, verbose_name="beneficio")),
                (
                    "position",
                    models.PositiveSmallIntegerField(default=0, verbose_name="orden"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefits",
                        to="products.product",
                        verbose_name="producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "beneficio",
                "verbose_name_plural": "beneficios",
                "ordering": ["position", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "icon"), name="unique_product_benefit_icon"
                    )
                ],
            },
        ),
    ]
